title: A book about IT for non-IT people
description: Have you ever wondered what dark magic the famous IT is about?

# Build settings
baseurl:                /it.nonit
url:                    https://promne.github.io

# Collections
collections:
  chapters:
    output: true

# Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default